/**
 * Converts the original's decoded export into `src/levels/rooms.generated.ts`, and writes one room's
 * source record beside the converter as the fixture the suite asserts against.
 *
 * **The export is not in this tree**, so this script is run by hand, pointed at wherever the export
 * is kept, and what it produces is committed. Nothing in the application or the suite runs it, and
 * nothing at build time does — the rooms in the tree are the rooms that ship. That is
 * doc/spec-tech.md's **A-3**, and this script is the whole of what it asks for.
 *
 *   node scripts/import-rooms.ts <path to traz_rooms_all.json>
 *
 * Node runs this file directly; the types are stripped rather than compiled.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { convertRoom, type SourceRoom } from '../src/import/convert.ts';
import type { ImportedRoom } from '../src/levels/room-notation.ts';

/**
 * The room whose source record is committed as the converter's fixture: the one room that places
 * every object kind the export uses, so a mistake in any kind fails the assertion.
 */
const FIXTURE_ROOM = 24;

const GENERATED = 'src/levels/rooms.generated.ts';
const FIXTURE = `src/import/room-${FIXTURE_ROOM}.source.json`;

function literal(value: string | number | undefined): string {
  if (value === undefined) return 'undefined';
  return typeof value === 'number' ? String(value) : JSON.stringify(value);
}

function roomSource(room: ImportedRoom): string {
  const bats = room.bats
    .map((bat) => {
      const column = bat.orientation === 'horizontal' ? bat.position / 32 : bat.line;
      const row = bat.orientation === 'horizontal' ? bat.line : bat.position / 32;
      return `b('${bat.orientation}', ${column}, ${row})`;
    })
    .join(', ');

  const elements = room.elements
    .map(
      (item) =>
        `    e('${item.kind}', ${item.column}, ${item.row}, ` +
        `${item.footprint.columns}, ${item.footprint.rows}, ${literal(item.colorId)}),`,
    )
    .join('\n');

  const ballStart =
    room.ballStart === undefined
      ? 'undefined'
      : `{ column: ${room.ballStart.column}, row: ${room.ballStart.row} }`;

  return [
    '  {',
    `    origin: { room: ${room.origin.room} },`,
    `    columns: ${room.columns},`,
    `    rows: ${room.rows},`,
    `    colorId: ${literal(room.colorId)},`,
    `    ballStart: ${ballStart},`,
    `    bats: [${bats}],`,
    '    elements: [',
    elements.replace(/^/gm, '  '),
    '    ],',
    '  },',
  ].join('\n');
}

function generatedSource(rooms: readonly ImportedRoom[]): string {
  return [
    '/**',
    ' * The original\'s rooms, converted once and committed.',
    ' *',
    ' * **Generated by `scripts/import-rooms.ts`. Edit that, or the export, never this file.**',
    ' *',
    ' * Every room the original has is here, including the ones no rule can play yet — a room left',
    ' * out would be a second place the rules are decided, and would hide how much of the original is',
    ' * still out of reach. `unplayableReasons` in the domain says which is which.',
    ' */',
    '',
    "import { bat as b, element as e, type ImportedRoom } from './room-notation';",
    '',
    'export const ROOMS: readonly ImportedRoom[] = [',
    rooms.map(roomSource).join('\n'),
    '];',
    '',
  ].join('\n');
}

const path = process.argv[2];
if (path === undefined) throw new Error('usage: node scripts/import-rooms.ts <traz_rooms_all.json>');

const export_ = JSON.parse(readFileSync(path, 'utf8')) as { readonly rooms: readonly SourceRoom[] };
const byNumber = new Map(export_.rooms.map((source) => [source.room_index, source]));
const numbers = [...byNumber.keys()].sort((left, right) => left - right);

const rooms = numbers.map((number) => {
  const source = byNumber.get(number);
  if (source === undefined) throw new Error(`the export has no room ${number}`);
  return convertRoom(source);
});

const fixtureSource = byNumber.get(FIXTURE_ROOM);
if (fixtureSource === undefined) throw new Error(`the export has no room ${FIXTURE_ROOM}`);

writeFileSync(GENERATED, generatedSource(rooms));
writeFileSync(FIXTURE, `${JSON.stringify(fixtureSource, null, 1)}\n`);

console.log(`${rooms.length} rooms -> ${GENERATED}`);
console.log(`room ${FIXTURE_ROOM}'s source record -> ${FIXTURE}`);
